language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - sudo apt-get install parallel
    - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - composer install --prefer-source
    - bin/composer install --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script:
    - ls -d tests/Composer/Test/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c tests/complete.phpunit.xml --coverage-php /tmp/coverage/{}.cov {};' || exit 1
    - phpcov merge --clover coverage.clover /tmp/coverage

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

git:
  depth: 5
